name: Terraform CI/CD

on:
#  push:
#    paths:
#      - '**.tf'
#      - '**.yaml'
#  pull_request:
#    types: [opened, reopened, synchronize, closed]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform:
    uses: './.github/workflows/terraform.yaml'
    with:
      working-directory: './terraform'
      environments-directory: './terraform/environments'
      modules-directory: './terraform/modules'
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_ORGANIZATION: ${{ secrets.TF_ORGANIZATION }}